
import * as appActions from './appActions'
import * as formActions from './formActions'

export const types = {
  INIT: "INIT",
  SET_LANGUAGE: "SET_LANGUAGE",
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
  EXECUTE: "EXECUTE",
  COMPLETED: "COMPLETED",
  CLOSE_ALERT: "CLOSE_ALERT",
  // form
  ADD_DATA_SOURCE: "ADD_DATA_SOURCE",
  UPDATE_DATA_SOURCE: "UPDATE_DATA_SOURCE",
  SELECT_DATA_SOURCE: "SELECT_DATA_SOURCE",
  SELECT_KEY_COLUMN: "SELECT_KEY_COLUMN",
  SELECT_TEXT_COLUMN: "SELECT_TEXT_COLUMN",
  CHANGE_ANALYZE_TYPE: "CHANGE_ANALYZE_TYPE",
  CHANGE_OUTPUT_MODE: "CHANGE_OUTPUT_MODE",
  CHANGE_OUTPUT_PROJECT_ID: "CHANGE_OUTPUT_PROJECT_ID",
  CHANGE_OUTPUT_DATASET_ID: "CHANGE_OUTPUT_DATASET_ID",
  CHANGE_OUTPUT_TABLE_ID: "CHANGE_OUTPUT_TABLE_ID",
  CHANGE_OUTPUT_DATA_SOURCE: "CHANGE_OUTPUT_DATA_SOURCE",
}

export {
  appActions,
  formActions,
}
